# -*- coding: utf-8 -*-
"""week3 A108260006 賴威丞.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Epqf6WJT5v4R4A4ziNxBv36GnK6C_3A
"""

print("Hello world")

print("I'm 賴威丞")